export const LAYOUT = {
  postItNotes: {
    width: 160,
    height: 160,
    spacing: 180,
    startY: 180,
    rotations: [-2, 3, -2, 3, -2],
  },
  cards: {
    pink: {
      width: 320,
      height: 480,
      rotation: 1,
    },
    cyan: {
      width: 400,
      height: 400,
      rotation: -1,
    },
    lostDino: {
      width: 300,
      height: 420,
      rotation: 3,
    },
  },
  stickers: [
    {
      src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image%2024-95Kr82qUMQVTjhXn3p3Hm1ts8Ctqst.png",
      alt: "Apocalypse",
      width: 150,
      height: 60,
      x: 720,
      y: 680,
      rotation: 0,
    },
    {
      src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image%2016-XKqR9NvtnSh9iC1GlqN6TgB4Wvs4v3.png",
      alt: "Crying Ghost",
      width: 80,
      height: 80,
      x: 1200,
      y: 120,
      rotation: 0,
    },
    {
      src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image%2017-fw74XWQbvJRiZJsJKZDc5pXyuvCgsl.png",
      alt: "Circle Eyes",
      width: 80,
      height: 80,
      x: 380,
      y: 220,
      rotation: 0,
    },
    {
      src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image%2022-RDS0Ns0TYjaIugETzbyp4zLKz4KUbb.png",
      alt: "Bubble Tea Dino",
      width: 80,
      height: 80,
      x: 920,
      y: 580,
      rotation: 0,
    },
    {
      src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image%2025-P12OMc7ZFOadg7PMqHBHxJ7PImsGES.png",
      alt: "Hackers Assemble",
      width: 100,
      height: 80,
      x: 880,
      y: 320,
      rotation: 0,
    },
    {
      src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image%2021-6wmn6I7SOyATb6lw9eRLuHNFcmJwRY.png",
      alt: "Dynamic Dino",
      width: 80,
      height: 80,
      x: 120,
      y: 420,
      rotation: 0,
    },
    {
      src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image%2020-9GwZeMbJ8UXU0wQ2ckJEgCPx6SaKdA.png",
      alt: "Purple Fox",
      width: 80,
      height: 80,
      x: 40,
      y: 580,
      rotation: 0,
    },
  ],
  banner: {
    width: 400,
    height: 120,
    x: 40,
    y: 40,
  },
  hackClubFlag: {
    width: 180,
    height: 120,
  },
}

